version: "3"

services:

    client:
        container_name: ustrareact
        build:
            context: ./ustrareact
            dockerfile: dev.dockerfile
        environment:
            HOST: 0.0.0.0
        ports:
            - 5003:5003
        volumes:
            - ./ustrareact:/src/client/app
        working_dir: /src/client/app
        env_file:
            - ./ustrareact/.env